- infrastructure/config-default.cfg
- web/src/p2k16/core/label.py
- web/src/p2k16/web/label_blueprint.py
- web/src/p2k16/web/server.py
- web/src/p2k16/web/static/my-profile.html
- web/src/p2k16/web/static/p2k16/p2k16.js
- web/src/p2k16/web/templates/base.html
The idea is that each member box at bitraf should have a label with a QR
code for quickly checking payment status, and with contact information
if payment has lapsed, making easier to keep the member storage clean
and with some available space.
This code adds a button to your personal profile that lets you print
such a label, by sending a message via MQTT with the information needed
to print a label. Elias is working on the component that will listen for
those messages and do the actual printing and label creation.
The idea of using MQTT is to keep p2k16 low on dependencies, and to not
have it do things that isnt "core".
> Add a "Print box label" button to "My profile"

- web/src/p2k16/web/static/tool-front-page.html
Adds Block to get even sized buttons. Adds Danger-style to get red buttons for checked out tools. Moved personal checkouts down, since they don't seem to be useful. We can delete them later.
> Fix for #61: make it easy to see that a tool is checked out

- web/src/p2k16/core/event_management.py
This makes the page show last seen and not first seen, fixing #51
> fix #51: Order desc when finding last door event

- web/src/p2k16/web/static/p2k16/p2k16.js
They now disapear after 5 seconds, but that can be adjusted. I chose to
not dismiss error popups by default, since they hopefully are more
important.
This will break in IE11 unless #68 is merged as well
Fixes #65
> Add timeout for dismissing info-popups

- web/src/p2k16/web/core_blueprint.py
- web/src/p2k16/web/static/user-detail.html
This is only shown in the viewer is in the admin circle. It shows
nothing but the fee for now, but first_date and start_date are in the
data sent to the client for admins if that is interesting.
> Show membership fee on public profile page

- web/src/p2k16/web/static/admin-account-detail.html
Probably a bug from the account changes this spring, but there was an
`.account` to much to get the membership details and fee.
> Show membership fee on details page again

- web/src/p2k16/core/account_management.py
Will give a bit better error messages to the admin when trying to add
someone that is already a member or try to remove someone that has
already been removed.
Fixes #34
> Add assert for circle membership on add and remove

- web/bower.json
- web/src/p2k16/web/templates/base.html
This fixes most IE11/Edge and some other issues that stems from using
modern javascript features. Makes it a bit less tedious to write client
code.
We could maintain our own polyfill-library if people dislike external
services, but then we would end up serving the same one to everyone most
likely, which seems like a waste.
Fixes at least #53
https://polyfill.io/v3/url-builder/ to reconfigure or add/remove features.
> Add polyfill using polyfill-as-a-service

- web/src/p2k16/core/account_management.py
It seems usernames shouldn't be emails, this blocks this in a crude way
by checking if the username contains `@` and raises an user-exception if
it does, stopping signup with a semi-descriptive error message.
No longer fixes #43, as its not a bug.
Make checks on username stricter in any case, but allow emails.
> Checks username for `@` and ` ` on signup

- web/src/p2k16/core/mail/__init__.py
- web/src/p2k16/core/membership_management.py
- web/src/p2k16/web/server.py
- web/src/p2k16/web/static/front-page.html
Show Manage billing button at all times. This fixes the case that an expired membership cannot be changed.
Should be better handled on frontend to display a message that membership is active, but unpaid.
Also, enable signup email to be sent to a specific address to avoid spamming post@bitraf.no during testing.
> Stripe quickfix

- web/src/p2k16/web/core_blueprint.py
- web/src/p2k16/web/static/user-detail.html
There was a problem with looking at membership, as that is no longer
updated when payment it stopped. Now we simply check StripePayment
and employee-status and show that instead.
> Show correct paying member status on profile-page

- web/src/p2k16/core/authz_management.py
- web/src/p2k16/core/door.py
This allows us to have a set of circles for each door, and without
membership in that circle, you wont be able to open that door.
This check does not apply to employees of companies, only for paying
members.
If you attempt to open multiple doors, none will open if you lack any of
the circles.
For now all doors have `door` only, this is intended used at BV9 to
limit access to certain areas.
https://github.com/bitraf/infrastructure/issues/149
> Add support for different circles for each door

- .gitlab-ci.yml
- requirements.txt
- web/src/p2k16/core/authz_management.py
- web/test/p2k16/test_authz_management.py
We simplify a bit by checking payment and employee status first.
Employee have access to all doors, non-paying members have access to no
doors, so we can get that out of the way first.
Once we have done that, we check better that the account is a member of
at least one of the circles on a door, if there is no overlap of
circles, the whole request is denied.
> More correct door authz handling

- web/src/p2k16/web/static/admin-account-list.html
- web/src/p2k16/web/static/admin.html
- web/src/p2k16/web/static/p2k16/p2k16.js
When listing all accounts for /admin/account, the current query is very
slow because it 1) loads all data for each profile, and 2) the loading
of all profiles is done in a separate query.
As an easy fix, use the non-full version of the account list. With this
change the "fee" column is dropped.
Fixes #130.
> fix: Use better profile list

- README.md
- web/src/p2k16/web/static/about.html
- web/src/p2k16/web/static/tool-front-page.html
@trygvis This super simple PR is a follow-up to my most recent one, most notably to NOT disable tool buttons based on who check out the tool, i.e. reverting back to how it was before.
> Minor quick fixes 202208

- web/src/p2k16/web/static/tool-front-page.html
The button showed when not the checked out user had no action attached
so nothing would happen.
Reduced to one button again since they were the same.
Removed invalid part of the id attribute as it didn't seem to do
anything.
> Fix tool check-in button for other users

- web/src/p2k16/web/tool_blueprint.py
- web/src/p2k16/web/utils.py
A few places we require a specific circle to perform operations, but the error message you get when that happens is a very generic "read only" message, leaving the user confused.
This will make the error message a better "You are not a member of circle `N`", leaving the user with a path forward.
> Return a better error message when missing circle

- web/src/p2k16/web/static/tool-front-page.html
In the UI refresh we lost a confirmation for checking in (or out) a tool that you as the current user did not "own". This re-adds this confirmation.
Fixes #136
> Re-enable confirmation for non-owned tools

- migrations/V001.031__stripe_drop_unique.sql
- web/src/p2k16/core/membership_management.py
- web/src/p2k16/core/models.py
This closes issue #122 related to how Stripe changed their billing of prorations about 1 year ago.
Finally tested ok in staging. Requires a migration to deploy.
> Add support for stripe prorations

- requirements.txt
- web/src/p2k16/core/membership_management.py
- web/src/p2k16/web/core_blueprint.py
- web/src/p2k16/web/membership_blueprint.py
- web/src/p2k16/web/static/core-data-service.js
- web/src/p2k16/web/static/front-page.html
- web/src/p2k16/web/static/p2k16/p2k16.js
This is the first of a 2-stage approach to increase the membership prices as voted on in the general assembly. The second stage will adjust prices for existing members.
Membership prices are now managed as Stripe products and can be updated there in the future. Stripe also contain the associated 'features' listed on the front page.
This PR also closes #124 by adding a retry payment button on the front page if there are unpaid invoices.
Tested for regressions on staging.
> Move membership price from code to stripe model

- web/src/p2k16/web/core_blueprint.py
The `insight-fee` circle might be missing in local environments, no need to die, we just won't show the insight info
> More resilient lookup of a circle

- web/src/p2k16/web/static/user-detail.html
The email wasn't display on the profile page, because it used the wrong reference in the code
> fix display of email
